{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.nextftc",
    "module": "nextcontrol",
    "version": "0.0.0-alpha1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "nextcontrol-0.0.0-alpha1.jar",
          "url": "nextcontrol-0.0.0-alpha1.jar",
          "size": 33690,
          "sha512": "f29ad0aa5e656678be7859f5dfbfdfe3519c5ae5bb10275174f02f2fe346ff72f9f566077946693db62b94f0693bef11898f30761ddacd9c7d9dd48890e893b0",
          "sha256": "d2b2cfa856a3c372f5da820e7c3656b47b4b2e7cab598df4dd5a26286e563802",
          "sha1": "388d0739f1c4c066e57a1b2c6e4ece059b68db35",
          "md5": "e114e76b33fb232d45c2ed68c70bd079"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.21"
          }
        }
      ],
      "files": [
        {
          "name": "nextcontrol-0.0.0-alpha1.jar",
          "url": "nextcontrol-0.0.0-alpha1.jar",
          "size": 33690,
          "sha512": "f29ad0aa5e656678be7859f5dfbfdfe3519c5ae5bb10275174f02f2fe346ff72f9f566077946693db62b94f0693bef11898f30761ddacd9c7d9dd48890e893b0",
          "sha256": "d2b2cfa856a3c372f5da820e7c3656b47b4b2e7cab598df4dd5a26286e563802",
          "sha1": "388d0739f1c4c066e57a1b2c6e4ece059b68db35",
          "md5": "e114e76b33fb232d45c2ed68c70bd079"
        }
      ]
    }
  ]
}
