{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rowanmcalpin.nextftc",
    "module": "pedro",
    "version": "0.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "pedro-0.5.9.aar",
          "url": "pedro-0.5.9.aar",
          "size": 15101,
          "sha512": "bd8f771a9941917253b35d7103ea7646f96f81c3841d816a0c9d80f713157c693fa9deeb3b3e95331ed746bf448bff775c21d0ecec957935c7c01dd21dbbc32c",
          "sha256": "51fc8f595ad84bf84597ce1f1331d3fc2f7372708eaa35bb1ecb42515f272f37",
          "sha1": "2186b78ab2ef08c90a3f6773b32e132703c351e4",
          "md5": "0071bd1d33d9e4da5b586bb2fb4c2720"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.2.0"
          }
        },
        {
          "group": "com.rowanmcalpin.nextftc",
          "module": "core",
          "version": {
            "requires": "0.5.9"
          }
        },
        {
          "group": "com.rowanmcalpin.nextftc",
          "module": "ftc",
          "version": {
            "requires": "0.5.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "pedro-0.5.9.aar",
          "url": "pedro-0.5.9.aar",
          "size": 15101,
          "sha512": "bd8f771a9941917253b35d7103ea7646f96f81c3841d816a0c9d80f713157c693fa9deeb3b3e95331ed746bf448bff775c21d0ecec957935c7c01dd21dbbc32c",
          "sha256": "51fc8f595ad84bf84597ce1f1331d3fc2f7372708eaa35bb1ecb42515f272f37",
          "sha1": "2186b78ab2ef08c90a3f6773b32e132703c351e4",
          "md5": "0071bd1d33d9e4da5b586bb2fb4c2720"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "pedro-0.5.9-sources.jar",
          "url": "pedro-0.5.9-sources.jar",
          "size": 16463,
          "sha512": "a6048d9793d58307d7478297c6d6c5855661df1f7ce055d8c38efd969e1518faee4d2c53f4f74eb7bbafa25bc53aa3ece710121ac026368e59511d554bc9de8e",
          "sha256": "763f837d87ab9505cd10bd324de6846f55504fb9a9530d6ec415ce03edd06baf",
          "sha1": "b25aeb45e1b09b9a55abd2b317b6ef9c30559a14",
          "md5": "5ef513a00b8638c9da0ed6793c07b523"
        }
      ]
    }
  ]
}
