{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rowanmcalpin.nextftc",
    "module": "ftc",
    "version": "0.5.0-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-0.5.0-beta1.aar",
          "url": "ftc-0.5.0-beta1.aar",
          "size": 75846,
          "sha512": "e6a25aaed4057d6cbe42fce499a5e72acd9adab6fb13efe44e52c8552dd738bd9a078c77f691040dfd80d2a2a0e418e43b2b24bddc7bc11630359b103645a4e0",
          "sha256": "bcaa1b64168569b799ddc71494dd23ae7305179de589aa867530a5906e8b8dd7",
          "sha1": "cc5d5b01c26855efc9566bd71ba4d53e775a0793",
          "md5": "7c4e07b41b7ab6aacfc06acac69b3e3f"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.10.1"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.10.0"
          }
        },
        {
          "group": "com.rowanmcalpin.nextftc",
          "module": "core",
          "version": {
            "requires": "0.5.0-beta1"
          }
        },
        {
          "group": "com.pedropathing",
          "module": "pedro",
          "version": {
            "requires": "0.0.1-beta13"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-0.5.0-beta1.aar",
          "url": "ftc-0.5.0-beta1.aar",
          "size": 75846,
          "sha512": "e6a25aaed4057d6cbe42fce499a5e72acd9adab6fb13efe44e52c8552dd738bd9a078c77f691040dfd80d2a2a0e418e43b2b24bddc7bc11630359b103645a4e0",
          "sha256": "bcaa1b64168569b799ddc71494dd23ae7305179de589aa867530a5906e8b8dd7",
          "sha1": "cc5d5b01c26855efc9566bd71ba4d53e775a0793",
          "md5": "7c4e07b41b7ab6aacfc06acac69b3e3f"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftc-0.5.0-beta1-sources.jar",
          "url": "ftc-0.5.0-beta1-sources.jar",
          "size": 36595,
          "sha512": "2985864d829039bfa666daf7cbcbcdbd5ac872d19641a07f1d0c3245d5b0ff6060e2f49140087d189607955b4251e10707767089a1cb810344a96ce033c7b190",
          "sha256": "e12d82ad1e39c6ae4ff62889ada1ffdd79b3153e7ee4ac04ce37f530fb0ec5f7",
          "sha1": "c8bcd6e3bd86532a8c2365dcfe90221d3c4d7c8d",
          "md5": "e4bdaf877c52858abb2bf425ec28f945"
        }
      ]
    }
  ]
}
