{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rowanmcalpin.nextftc",
    "module": "core",
    "version": "0.4.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-0.4.4.aar",
          "url": "core-0.4.4.aar",
          "size": 204711,
          "sha512": "889d49ce47778f84f543da33a027b519103e93f531d679c3de962f2bd801f725394a5c2b20e5bd836c9467649a06ab49efcf0ce80d6fd9c1ba6075ba37b2851e",
          "sha256": "649c6699d6872f48638136633c25126cdeb0f1392f6d2fab45d0b039240ef475",
          "sha1": "1ebdd2d6cd8d153ff404a4565491792d575a7afa",
          "md5": "12c2ed48deba7a354121278c10aec00d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.16"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.acmerobotics.roadrunner",
          "module": "core",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "com.github.rh-robotics",
          "module": "MeepMeep",
          "version": {
            "requires": "v1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.4.4.aar",
          "url": "core-0.4.4.aar",
          "size": 204711,
          "sha512": "889d49ce47778f84f543da33a027b519103e93f531d679c3de962f2bd801f725394a5c2b20e5bd836c9467649a06ab49efcf0ce80d6fd9c1ba6075ba37b2851e",
          "sha256": "649c6699d6872f48638136633c25126cdeb0f1392f6d2fab45d0b039240ef475",
          "sha1": "1ebdd2d6cd8d153ff404a4565491792d575a7afa",
          "md5": "12c2ed48deba7a354121278c10aec00d"
        }
      ]
    }
  ]
}
