{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rowanmcalpin.nextftc",
    "module": "ftc",
    "version": "0.5.3-beta2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-0.5.3-beta2.aar",
          "url": "ftc-0.5.3-beta2.aar",
          "size": 85630,
          "sha512": "31d3283ee4e4015b9ea7bee93b01fc0c4b86af79288977c0481cb337babb29337dfc77fe192b481755570ba0b71293a0663fadd7310d2daba7fff8cbd7ea0d8f",
          "sha256": "f9091fcbf3d2e8ce55ac2b550cb5ef2c0d4ac6a446c47f8309c96d0d250174f8",
          "sha1": "124c4568bdb6078d812b77f9229e852a385211b5",
          "md5": "05a814b5ffa2e670b55af9a49d43d5a9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.rowanmcalpin.nextftc",
          "module": "core",
          "version": {
            "requires": "0.5.3-beta1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-0.5.3-beta2.aar",
          "url": "ftc-0.5.3-beta2.aar",
          "size": 85630,
          "sha512": "31d3283ee4e4015b9ea7bee93b01fc0c4b86af79288977c0481cb337babb29337dfc77fe192b481755570ba0b71293a0663fadd7310d2daba7fff8cbd7ea0d8f",
          "sha256": "f9091fcbf3d2e8ce55ac2b550cb5ef2c0d4ac6a446c47f8309c96d0d250174f8",
          "sha1": "124c4568bdb6078d812b77f9229e852a385211b5",
          "md5": "05a814b5ffa2e670b55af9a49d43d5a9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftc-0.5.3-beta2-sources.jar",
          "url": "ftc-0.5.3-beta2-sources.jar",
          "size": 40519,
          "sha512": "6454e2b3a995a08372d05fd72a17766819428d4b5bd878f4c66a6312cb4a231ddc62b7e117009f73bd1fd5ceac146eedbbf2e8fbe9c10d14b0d4765eeffe7fc6",
          "sha256": "ea1e65c135cb970c3e1c0e9573edbf3a9e59dd900bfbdbae2c7067b6df6d1c66",
          "sha1": "278aa013fafe30ee4712f7d9da71e5a8a763bd61",
          "md5": "56b307656f04e279816c42dd8a7f1484"
        }
      ]
    }
  ]
}
