{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rowanmcalpin",
    "module": "nextftc",
    "version": "0.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nextftc-0.1.1.aar",
          "url": "nextftc-0.1.1.aar",
          "size": 188549,
          "sha512": "9c39626d46a2f4da3d0a821663a1bbe04c0aa2e8a22deebb42c6ed303c71a4fb1fa824caff6549a07a619f6eee37240063cd44251fe1c0bc478dd2e32d605016",
          "sha256": "937425f6824b1f4e739f5e1ecd373bf223e1a26c5fbfec10afe4b2a09a85b5dc",
          "sha1": "cde6efaab811d2200d90e5c0a2f8a2e1e84b49e6",
          "md5": "f9b0b9be040868c10a5e0c622a5f528f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.6"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.acmerobotics.roadrunner",
          "module": "core",
          "version": {
            "requires": "0.5.5"
          }
        },
        {
          "group": "com.github.NoahBres",
          "module": "MeepMeep",
          "version": {
            "requires": "2.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.10"
          }
        }
      ],
      "files": [
        {
          "name": "nextftc-0.1.1.aar",
          "url": "nextftc-0.1.1.aar",
          "size": 188549,
          "sha512": "9c39626d46a2f4da3d0a821663a1bbe04c0aa2e8a22deebb42c6ed303c71a4fb1fa824caff6549a07a619f6eee37240063cd44251fe1c0bc478dd2e32d605016",
          "sha256": "937425f6824b1f4e739f5e1ecd373bf223e1a26c5fbfec10afe4b2a09a85b5dc",
          "sha1": "cde6efaab811d2200d90e5c0a2f8a2e1e84b49e6",
          "md5": "f9b0b9be040868c10a5e0c622a5f528f"
        }
      ]
    }
  ]
}
