{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rowanmcalpin.nextftc",
    "module": "core",
    "version": "0.4.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-0.4.2.aar",
          "url": "core-0.4.2.aar",
          "size": 204706,
          "sha512": "c7a4fdafcd4468c8bbc56ac22908fec4e097dbd73c9cf4746aad60df479451c2f8fc47f21e3966bdf3df1507d32c8034dd7f12f157725b12363c7afac06fef1f",
          "sha256": "a47e5f384b3a438ed81528d64db1274f148001275091fc7a559fb4041eafe19e",
          "sha1": "d128a3ab6110fe6f9b68e82ba0d10f480ea5e575",
          "md5": "e8c98aa0b65d063d0716736ad9206212"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.6"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.acmerobotics.roadrunner",
          "module": "core",
          "version": {
            "requires": "0.5.6"
          }
        },
        {
          "group": "com.github.rh-robotics",
          "module": "MeepMeep",
          "version": {
            "requires": "v1.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.4.2.aar",
          "url": "core-0.4.2.aar",
          "size": 204706,
          "sha512": "c7a4fdafcd4468c8bbc56ac22908fec4e097dbd73c9cf4746aad60df479451c2f8fc47f21e3966bdf3df1507d32c8034dd7f12f157725b12363c7afac06fef1f",
          "sha256": "a47e5f384b3a438ed81528d64db1274f148001275091fc7a559fb4041eafe19e",
          "sha1": "d128a3ab6110fe6f9b68e82ba0d10f480ea5e575",
          "md5": "e8c98aa0b65d063d0716736ad9206212"
        }
      ]
    }
  ]
}
