{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rowanmcalpin.nextftc",
    "module": "core",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-0.2.2.aar",
          "url": "core-0.2.2.aar",
          "size": 191719,
          "sha512": "d6c0585b1f5842e21b893fd979504102c9e60773dc57ab71ddd3aa076c352f18cceb18728e890ce9f4ac7bc66f6896f15c777c95ecf3e139acc88e30a959ec8e",
          "sha256": "e2a7deee5e1aab6fba2fd3a5638dbe9cd9c4ad482acd94d3721284b7d2425123",
          "sha1": "b6e299b0f7060eff566ea15b2775533ae0544726",
          "md5": "6c80e9bfc8c144b5c22f39d6a42bc1f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.6"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.acmerobotics.roadrunner",
          "module": "core",
          "version": {
            "requires": "0.5.5"
          }
        },
        {
          "group": "com.github.NoahBres",
          "module": "MeepMeep",
          "version": {
            "requires": "-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.2.2.aar",
          "url": "core-0.2.2.aar",
          "size": 191719,
          "sha512": "d6c0585b1f5842e21b893fd979504102c9e60773dc57ab71ddd3aa076c352f18cceb18728e890ce9f4ac7bc66f6896f15c777c95ecf3e139acc88e30a959ec8e",
          "sha256": "e2a7deee5e1aab6fba2fd3a5638dbe9cd9c4ad482acd94d3721284b7d2425123",
          "sha1": "b6e299b0f7060eff566ea15b2775533ae0544726",
          "md5": "6c80e9bfc8c144b5c22f39d6a42bc1f8"
        }
      ]
    }
  ]
}
