{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rowanmcalpin.nextftc",
    "module": "core",
    "version": "0.4.1-beta",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "core-0.4.1-beta.aar",
          "url": "core-0.4.1-beta.aar",
          "size": 197651,
          "sha512": "ff6b12a5149ec8393dd88cbe40bd7e7ea226f194b6f6cf4c9bc932a02e1a13901813159761f28053b50ef020625d883d4f4ffb1dd458742c9bff82b3e417c8ed",
          "sha256": "4dd71119f0aa3abdc78577fbfcc5535e5ed7910d72e0f79ef167ad637c39aedd",
          "sha1": "acf63b9e7d41701323d0f4fdab76dab8700e37db",
          "md5": "b89c7bf97893d234d3b71a5a32178771"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.acmerobotics.dashboard",
          "module": "dashboard",
          "version": {
            "requires": "0.4.6"
          },
          "excludes": [
            {
              "group": "org.firstinspires.ftc",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.acmerobotics.roadrunner",
          "module": "core",
          "version": {
            "requires": "0.5.5"
          }
        },
        {
          "group": "com.github.rowan-mcalpin",
          "module": "MeepMeep-1",
          "version": {
            "requires": "actualworking"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.20"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.4.1-beta.aar",
          "url": "core-0.4.1-beta.aar",
          "size": 197651,
          "sha512": "ff6b12a5149ec8393dd88cbe40bd7e7ea226f194b6f6cf4c9bc932a02e1a13901813159761f28053b50ef020625d883d4f4ffb1dd458742c9bff82b3e417c8ed",
          "sha256": "4dd71119f0aa3abdc78577fbfcc5535e5ed7910d72e0f79ef167ad637c39aedd",
          "sha1": "acf63b9e7d41701323d0f4fdab76dab8700e37db",
          "md5": "b89c7bf97893d234d3b71a5a32178771"
        }
      ]
    }
  ]
}
