{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rowanmcalpin.nextftc",
    "module": "pedro",
    "version": "0.5.10-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "pedro-0.5.10-beta1.aar",
          "url": "pedro-0.5.10-beta1.aar",
          "size": 15209,
          "sha512": "ccba43911df24ec99ae2d8eb7604d34eaaf1792c4a2f2cc238326f1574e32164131dd45d1a910db974aad22a66bef949380dc00084ea3caf89fb579c8e86c743",
          "sha256": "f8a5197d055c818f7413e605485019729ae85846bdaffaa4e18ce69b5b7d9cfe",
          "sha1": "b253eb3f370c218241883ecbdb0a82662a2a9c12",
          "md5": "dd94efca6325e3a449840f3ce8e6554b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.1.1"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.1.1"
          }
        },
        {
          "group": "com.rowanmcalpin.nextftc",
          "module": "core",
          "version": {
            "requires": "0.5.10-beta1"
          }
        },
        {
          "group": "com.rowanmcalpin.nextftc",
          "module": "ftc",
          "version": {
            "requires": "0.5.10-beta1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "pedro-0.5.10-beta1.aar",
          "url": "pedro-0.5.10-beta1.aar",
          "size": 15209,
          "sha512": "ccba43911df24ec99ae2d8eb7604d34eaaf1792c4a2f2cc238326f1574e32164131dd45d1a910db974aad22a66bef949380dc00084ea3caf89fb579c8e86c743",
          "sha256": "f8a5197d055c818f7413e605485019729ae85846bdaffaa4e18ce69b5b7d9cfe",
          "sha1": "b253eb3f370c218241883ecbdb0a82662a2a9c12",
          "md5": "dd94efca6325e3a449840f3ce8e6554b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "pedro-0.5.10-beta1-sources.jar",
          "url": "pedro-0.5.10-beta1-sources.jar",
          "size": 16573,
          "sha512": "08b7fc75d8f753ded1d868a4b32a1ecbae56a3d25f9c57d5f0de5ebeb1331cd00e70f3392d92efbcdaef8c4f823cb382876d160153fd292ab60fd9c377a2097e",
          "sha256": "8d72da30aa3e000c3e0d1f8762b9386cda41459a17f36d682738f87689b81bae",
          "sha1": "50dfcfe1614d63b03c9729407d478352c863f81a",
          "md5": "77c2a1311a58da2c68d118905d3dad48"
        }
      ]
    }
  ]
}
