{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rowanmcalpin.nextftc",
    "module": "pedro",
    "version": "0.6.0-dev-components",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "pedro-0.6.0-dev-components.aar",
          "url": "pedro-0.6.0-dev-components.aar",
          "size": 12032,
          "sha512": "28a67804dd4b712f78d22514760bfdffe511336c5c8b2750b768ee92de544759d3c54164f38308e03f087d1c82a967e7b83f4b27e3c205abe7cd9815245fde1f",
          "sha256": "42a6b2f58f39020b494bee508d9f4ee16d19ce3294ab9238c3eb9b398e84c960",
          "sha1": "3c7d5d552fd2f3559f77d0f5b4e6dfcc3aace52c",
          "md5": "809283060da0caf1a1874de630092240"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.firstinspires.ftc",
          "module": "Hardware",
          "version": {
            "requires": "10.1.1"
          }
        },
        {
          "group": "org.firstinspires.ftc",
          "module": "RobotCore",
          "version": {
            "requires": "10.1.1"
          }
        },
        {
          "group": "com.rowanmcalpin.nextftc",
          "module": "core",
          "version": {
            "requires": "0.6.0-dev-components"
          }
        },
        {
          "group": "com.rowanmcalpin.nextftc",
          "module": "ftc",
          "version": {
            "requires": "0.6.0-dev-components"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.9.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "pedro-0.6.0-dev-components.aar",
          "url": "pedro-0.6.0-dev-components.aar",
          "size": 12032,
          "sha512": "28a67804dd4b712f78d22514760bfdffe511336c5c8b2750b768ee92de544759d3c54164f38308e03f087d1c82a967e7b83f4b27e3c205abe7cd9815245fde1f",
          "sha256": "42a6b2f58f39020b494bee508d9f4ee16d19ce3294ab9238c3eb9b398e84c960",
          "sha1": "3c7d5d552fd2f3559f77d0f5b4e6dfcc3aace52c",
          "md5": "809283060da0caf1a1874de630092240"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "pedro-0.6.0-dev-components-sources.jar",
          "url": "pedro-0.6.0-dev-components-sources.jar",
          "size": 14137,
          "sha512": "5f68f1cd10f73e992012e36d91e9aacd399dfed1cd01c16685ef0eadfe8e7beb8f33953424d8ae24bd716752b1778f13dcffdc85f8dfeea45c552810c0326f0b",
          "sha256": "6cfe717b75f546a42b2c3e85997be10e88e430097379a2ed7f945c0a9145b7b9",
          "sha1": "67773faa8a6ae9bd1716828a8ff67d54e384e53f",
          "md5": "b333415d6530c2c466a77d0cc52c0aa6"
        }
      ]
    }
  ]
}
