{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rowanmcalpin.nextftc",
    "module": "core",
    "version": "0.6.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.6.0.aar",
          "url": "core-0.6.0.aar",
          "size": 69942,
          "sha512": "fcd40fac79c944780823f257cc566bb8b65f6636c8d862a221043b685682ae1871619ea98555a2fafc09c17174fab5861e7cd1404633975909bc07c1cb67b494",
          "sha256": "599e50a9654c1c4fd46c2527a930e1bf9165d480732c1b0aa46769dd447ea472",
          "sha1": "7f451e16245c3ff7253df23980889f7628b8630d",
          "md5": "de4b973c38463580f46e1595bec735b9"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "core-0.6.0.aar",
          "url": "core-0.6.0.aar",
          "size": 69942,
          "sha512": "fcd40fac79c944780823f257cc566bb8b65f6636c8d862a221043b685682ae1871619ea98555a2fafc09c17174fab5861e7cd1404633975909bc07c1cb67b494",
          "sha256": "599e50a9654c1c4fd46c2527a930e1bf9165d480732c1b0aa46769dd447ea472",
          "sha1": "7f451e16245c3ff7253df23980889f7628b8630d",
          "md5": "de4b973c38463580f46e1595bec735b9"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "core-0.6.0-sources.jar",
          "url": "core-0.6.0-sources.jar",
          "size": 77395,
          "sha512": "fbb335f31d3d2e15de0a01793ecfca7f8a1a39f686d0f1d8837db97d91ba7803d86afdd0a398fb6cee6c958192240c837bc6c705221cf86b57db78ac34d6095b",
          "sha256": "7f1d05b0da69da5c040e990f35aec2ed514c11324baddfab6b7ebaeb404da091",
          "sha1": "62f75c1ea1b6a8bf87212f24af6adce050c48150",
          "md5": "8b981ac67f83584c5e2771fc733eca7d"
        }
      ]
    }
  ]
}
