{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rowanmcalpin.nextftc",
    "module": "ftc",
    "version": "0.5.9",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-0.5.9.aar",
          "url": "ftc-0.5.9.aar",
          "size": 109017,
          "sha512": "1fa6f8248d32c3978826ed38ddd8990c2b9f97f4697fdca02e992e7d3d8c7c95666d045bdbc2ab3bee338ac3879113cbce41f82052c8778cb959cefafa39f3ce",
          "sha256": "d859a4cc1add3727d76d29ad971ddf89e417594ceaba0b4a0645cd07c0627c36",
          "sha1": "fde3e034b8c03482d65698c3d56f7f6469a23817",
          "md5": "6e5c9ccfceeaf93fea1ce9285d3e1745"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.rowanmcalpin.nextftc",
          "module": "core",
          "version": {
            "requires": "0.5.9"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-0.5.9.aar",
          "url": "ftc-0.5.9.aar",
          "size": 109017,
          "sha512": "1fa6f8248d32c3978826ed38ddd8990c2b9f97f4697fdca02e992e7d3d8c7c95666d045bdbc2ab3bee338ac3879113cbce41f82052c8778cb959cefafa39f3ce",
          "sha256": "d859a4cc1add3727d76d29ad971ddf89e417594ceaba0b4a0645cd07c0627c36",
          "sha1": "fde3e034b8c03482d65698c3d56f7f6469a23817",
          "md5": "6e5c9ccfceeaf93fea1ce9285d3e1745"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftc-0.5.9-sources.jar",
          "url": "ftc-0.5.9-sources.jar",
          "size": 80591,
          "sha512": "f9a5843514cdd7bf45cf6d945089d7f3ca2ee9d0c799086a4fa1fef102645e7580d5cca676ea401a2cfdd870142311553d06668cec07d50f98fadd5ead17dfd3",
          "sha256": "9987569f05d45fa7eae6f1952cbba66cc8762aa8b4a06d9376e38df1c6f4d6c5",
          "sha1": "232e4dc537b27d4c48b10e53a145a16208a0c04e",
          "md5": "620470463d5f567d8c5bce3ae392ff1e"
        }
      ]
    }
  ]
}
