{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rowanmcalpin.nextftc",
    "module": "ftc",
    "version": "0.5.5-beta1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "releaseApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-0.5.5-beta1.aar",
          "url": "ftc-0.5.5-beta1.aar",
          "size": 99238,
          "sha512": "f4b06cb950b244eb7cc5cc78607b38fb02d70e17826b27f5b6b7e1a1049adde5a58a9f90d23dd21f04b0c9e38f081cc6d8e22cc1a99bd78c984b929a9fa2f4ef",
          "sha256": "241fc905fcdaae86136d7a36088ac01de3ba12a35904789cad5eb9c1653d188e",
          "sha1": "b17b699d24e11cbf66aee17100870f7ae96aa913",
          "md5": "9a20f8a39f2a34fc5acaf31ef163144b"
        }
      ]
    },
    {
      "name": "releaseRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "com.rowanmcalpin.nextftc",
          "module": "core",
          "version": {
            "requires": "0.5.5-beta1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "ftc-0.5.5-beta1.aar",
          "url": "ftc-0.5.5-beta1.aar",
          "size": 99238,
          "sha512": "f4b06cb950b244eb7cc5cc78607b38fb02d70e17826b27f5b6b7e1a1049adde5a58a9f90d23dd21f04b0c9e38f081cc6d8e22cc1a99bd78c984b929a9fa2f4ef",
          "sha256": "241fc905fcdaae86136d7a36088ac01de3ba12a35904789cad5eb9c1653d188e",
          "sha1": "b17b699d24e11cbf66aee17100870f7ae96aa913",
          "md5": "9a20f8a39f2a34fc5acaf31ef163144b"
        }
      ]
    },
    {
      "name": "releaseSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "files": [
        {
          "name": "ftc-0.5.5-beta1-sources.jar",
          "url": "ftc-0.5.5-beta1-sources.jar",
          "size": 80161,
          "sha512": "c3ba352990f5d77aa34419cc708bbdb2856438646ae9af8bbde24e1f71afd0018d9bebc0df0f1661b2231b6579b8a69cd28c75f6754d5fee85b655ad20d104a5",
          "sha256": "a960ba9443e5c0bdbbd7874d621fe1914b7ee7bf0f1f7d3dcff03175b6c589f0",
          "sha1": "c0e07833e5a602aea852e7348e2a282fa90743e5",
          "md5": "f95da78439a66ea8d656e13bfe482dec"
        }
      ]
    }
  ]
}
